### ISSUE TITLE
Неправильные первые твиты на сайте

### ISSUE THREAD

**Issue by kirelagin** [varya/catunderhood#3]
Чуть менее, чем у всех последних авторов, на сайте вместо первого твита показан последний с предыдущей недели, хотя в `authors.js`, вроде как, всё правильно.

![screen shot 2017-09-25 at 14 12 28](https://user-images.githubusercontent.com/451835/30805774-a5555524-a1fb-11e7-980e-91b4f1cd3d1f.png)

**Comment by varya** [comment]
Самопочинилось
